language: java

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  - unzip -qq apache-maven-3.3.9-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH

jdk:
- oraclejdk8

sudo: false
script: mvn clean install -Dmaven.test.skip=true

deploy:
  provider: releases
  api_key: 
	secure:
  file:
   - "rcp/org.eclipse.tracecompass.rcp.product/target/products/trace-compass-*.tar.gz"
   - "rcp/org.eclipse.tracecompass.rcp.product/target/products/trace-compass-*.zip"
  skip_cleanup: true
  on:
    tags: true
